# Generated by Django 4.2.4 on 2023-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='period_duration',
            field=models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], default='Days', max_length=10),
        ),
    ]
