# Generated by Django 4.2.4 on 2023-10-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.product'),
            preserve_default=False,
        ),
    ]
